
#
# This file has been modified by the Webis Group 
# to fit the needs of the IR Anthology. 
# The original is part of the ACL Anthology. 
#
title = "IR Anthology"
disablePathToLower = true
staticDir = ["static", "data-export"]

[permalinks]
  papers = "/:filename/"

[taxonomies]
  series = "series"

#https://sam.hooke.me/note/2018/03/hugo-tag-and-category-pages/